name: ğŸ‰  Notify On Release

on:
  release:
    types: [published]

jobs:
  discord-message:
    runs-on: ubuntu-latest
    steps:
      - name: âœ‰ï¸  Message to Discord
        uses: tsickert/discord-webhook@v0.0.7
        with:
          webhook-url: ${{secrets.DISCORD_WEBHOOK}}
          content: "New release: ${{ github.event.release.tag_name }} is out, [check it out now](${{ github.event.release.html_url }})"
